FROM node:18.7.0
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json package-lock.json ./
RUN npm install --silent
COPY . ./
RUN npm build

FROM nginx:latest
#WORKDIR /etc/nginx/conf.d
#COPY default.conf default.conf
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
#COPY $PWD/contact-appv1/build .
#EXPOSE 80
COPY --from=builder /app/build .
ENTRYPOINT ["nginx", "-g", "daemon off;"]

#FROM node:18.7.0
#WORKDIR /app
#EXPOSE 3000
#COPY package.json package-lock.json ./
#RUN npm install --silent
#COPY . ./
#CMD ["npm","start"]
